### ISSUE TITLE
Showing the line number of the error?

### ISSUE THREAD

**Issue by ryanelian** [wayneashleyberry/phplint#22]
Adding `-d display_errors=1` to the command line argument usually does it but I don't find a way to do it using this wrapper.

Any tips how to do it? Thanks.

**Comment by pyxze** [comment]
When you call phplint through this module you're not accessing it directly as you would on the command line, and the only parameter it is designed to accept is the files to process.

In the index.js file you'll notice that the lint.function only calls -l and the files (path). I updated this so that -d display_errors=1 is included by default as well to ensure that errors will be displayed.

Resources:

http://stackoverflow.com/questions/3339907/why-doesnt-lint-tell-me-the-line-number-and-nature-of-the-parse-error
